### ISSUE TITLE
Draft Participate Page

### ISSUE THREAD

**Issue by jj0hns0n** [codeforresilience/c4rsite#13]
http://codeforresilience.github.io/c4rsite/participate/

Should we include about how to partner?

**Comment by awyan1** [comment]
I think we should do "Participate" and "Contact us" as the same page. I don't think one would look for them separately, right? Motion to delete. 
They are combined for now here: https://docs.google.com/document/d/1efM5YJZ69IZBb7zAjRi4Oe7drwkMqZiOH-_dbKonsKU/edit?usp=sharing

**Comment by jj0hns0n** [comment]
Removing the participate page for now.
