### ISSUE TITLE
Draft Haiti Page

### ISSUE THREAD

**Issue by jj0hns0n** [codeforresilience/c4rsite#18]
http://codeforresilience.github.io/c4rsite/cities/port-au-prince

**Comment by awyan1** [comment]
https://docs.google.com/document/d/1zN310Y6kTFoEgpn7B2tFUZKXVSNFZw6pfnkSxmAukAM/edit?usp=sharing

**Comment by jj0hns0n** [comment]
Added here http://codeforresilience.github.io/c4rsite/projects/haiti.html
