### ISSUE TITLE
Verify Mission about and overview with Keiko and Adele

### ISSUE THREAD

**Issue by jj0hns0n** [codeforresilience/c4rsite#20]

**Comment by jj0hns0n** [comment]
@ks2693

**Comment by awyan1** [comment]
link: https://docs.google.com/document/d/1r5dCummdW7Vd-UtFSOQjM-251RkPWfDu1ADIzWkcHys/edit?usp=sharing

**Comment by jj0hns0n** [comment]
The entire text was added here http://codeforresilience.github.io/c4rsite/about/ the about section on the homepage on the right is this same text from the top, not sure what we do about the text on the right?
