### ISSUE TITLE
About text is getting cut

### ISSUE THREAD

**Issue by vdeparday** [codeforresilience/c4rsite#30]
![image](https://cloud.githubusercontent.com/assets/1036189/8315242/2cea9e8c-19bd-11e5-8534-6cc19c2bdf35.png)

**Comment by jj0hns0n** [comment]
Browser/OS/Screensize? But it should never be broken.

**Comment by vdeparday** [comment]
mac retina 15, displayed scaled with the text to be the smalled (highest resolution). It happens both on FF and Chrome, both latest version
