### ISSUE TITLE
CfR Home Page

### ISSUE THREAD

**Issue by jgbarbos** [codeforresilience/c4rsite#49]
Hi Cristiano, 
Few comments on the homepage (from top to bottom): 
1. Once we receive a high resolution copy of the logo it would be nice to put it on the site replacing the current logo but still leaving the slogan (Bridging communities for disaster resilience) as is. I don't believe the new logo has the slogan see preview attached.
   ![cfr new logo](https://cloud.githubusercontent.com/assets/15205614/12248121/58941d26-b885-11e5-81c0-853c3ce345a7.png)
2. It would be nice to set up the code for a 'transitioning banner' as we get pictures from the upcoming projects (Tanzania, Sri Lanka, Togo), and advertising UR 2016 (see picture attached - 
   ![ur2016_banner](https://cloud.githubusercontent.com/assets/15205614/12249082/912d02f0-b88b-11e5-9759-f14d0d6354f9.jpg). The UR picture should be for now linked to their web site: https://understandrisk.org/. What I mean by a transitioning banner is the picture slide show that some sites have as a banner.
3. The four images below the banner I think could be a bit larger
4. the titles of each of the four images I think should be linked to their respective content. Taking into consideration that the content link is already incorporated in the "read more" perhaps the same link in the title would be redundant. Thoughts?
5. Some items in the Activities section could be link to their respective content page. For example  "investing in expertise" could be linked to the Fellowship Program page; "Coding for Resilience" could be link to the Code Sprints page - I Figured this one out! DONE!
6. Current projects: the main thing here is the map. It would be nice to make an interactive map with added reference marks/pop-up labels on Togo, Sri Lanka, and Tanzania. More details Re: this map on a separate GitHub issue. 
7. The GFDRR and WBG logos at the bottoms should be Linked to their respective websites - I Figured this one out! DONE!

**Comment by cgiovando** [comment]
Fixed 1 and 4. Moving the rest to their own issues (2 --> #54 and 3 --> #55)

**Comment by jj0hns0n** [comment]
There is a spelling error (lounched ) in the tanzania description

**Comment by cgiovando** [comment]
fixed
