### ISSUE TITLE
CfR Homepage's Map

### ISSUE THREAD

**Issue by jgbarbos** [codeforresilience/c4rsite#50]
On to the map in the homepage (under "current projects")...
1. The Haiti label does not show anything in the map it self, simply a blank box. Either remove the box or add maybe a tiny picture of the Haiti team. Or the name of the App: SMS Lapli. same for Indonesia. The legend that shows underneath the map is fine but we should add the link where it sais "...read more..." - direct it to the Projects page. 
2. On the Map it self it would be ideal to add a label also to Sri Lanka, Tanzania, and Togo. Also add one if possible to Istanbul and label it UR 2016 (Link to their page for now (https://understandrisk.org/). For each project you can assign the space for a legend below (as it is currently for Haiti and Indonesia) in order to keep the flow. I can as we go write content for each one and we can just paste it onto the space on the back end. 
3. Finally for now, if you are up for it feel free to get creative with the map. Maybe switch it for a more visually appealing version. This is not necessary though, really all im concerned with is content.

**Comment by cgiovando** [comment]
I removed the popup and made the map smaller (reduced height to 270px).

Sri Lanka, Tanzania, Togo and UR 2016 are linked.

Closing for now, feel free to re-open if you think we should change the map style.
