### ISSUE TITLE
CfR New Logo low res.png

### ISSUE THREAD

**Issue by jgbarbos** [codeforresilience/c4rsite#53]
![cfr new logo low res](https://cloud.githubusercontent.com/assets/15205614/12310500/8e3d806c-ba1e-11e5-8960-b03767bc7d20.png)

**Comment by cgiovando** [comment]
@jgbarbos - what's this version of the logo for? Can you provide more details about this issue?

**Comment by jgbarbos** [comment]
Hi Cristiano, this is an extremely low resolution (old) version I was trying to upload to GitHub but could not :( The logo that should be uploaded is the one I sent to your email. Ideally would be nice to upload the logo to the img folder on our repository

**Comment by cgiovando** [comment]
OK, closing this then
